language: node_js
node_js:
  - 10
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
env:
  - PORT=9080
install:
  - npm i && npm run build
script:
  - npm run test