language: node_js
node_js:
- 10
cache:
  npm: true
  directories:
  - "~/.cache"
env:
- PORT=9080
install:
- npm i && npm run build
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_5f1908ef1e01_key -iv $encrypted_5f1908ef1e01_iv
  -in 2019_1_TheBang_id_rsa.pem.enc -out ./2019_1_TheBang_id_rsa.pem -d
