language: node_js
node_js:
- 10
cache:
  npm: true
  directories:
  - "~/.cache"
jobs:
  include:
    - stage: "E2E Tests"
      env:
      - PORT_TEST=9080
      script: npm run build && npm run test
    - stage: "Deploy DEV"
      if: branch = develop
      script: npm run build:dev && bash deploy-dev.sh
    - stage: "Deploy PROD"
      if: branch = master
      script: npm run build:prod && bash deploy-prod.sh
before_install:
- openssl aes-256-cbc -K $encrypted_5f1908ef1e01_key -iv $encrypted_5f1908ef1e01_iv
  -in 2019_1_TheBang_id_rsa.pem.enc -out ./2019_1_TheBang_id_rsa.pem -d
